### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by XIURongYao** [weiweiwei256/super-encourager#11]
![image](https://user-images.githubusercontent.com/22523826/90106493-149fff80-dd7a-11ea-8d05-5c145c47a0dd.png)

**Comment by Yapeng-Li** [comment]
我跟你一样哎 你的解决了吗

**Comment by lu592674374** [comment]
同不显示

**Comment by akakuz** [comment]
同样不显示，并且查看资源按钮之后无法弹出相应窗口。但是手动进入保存图片的文件夹中查看，图片都已经保存在本地。希望作者能修改一下

**Comment by suiteki** [comment]
一样的，什么时候更新啊？

**Comment by liar177** [comment]
哎这是我刚使用vscode下的插件，提示弹出来却显示不出图片很难受。。

**Comment by weiweiwei256** [comment]
谢谢各位的支持！！！  很不好意思   一直没时间支持   对不起各位

**Comment by weiweiwei256** [comment]
修复啦 不好意思 原因是：baidu做了修改禁止爬虫 另外 vscode 插件的通信协议也更新
