### ISSUE TITLE
图片没法展示 获取不到图片呢

### ISSUE THREAD

**Issue by FRZ5201314** [weiweiwei256/super-encourager#14]

**Comment by baininghan** [comment]
+1, 图片加载不出来~

**Comment by yuzai** [comment]
+1，我看本地是下载了图片了，但是就是展示不出来。
![image](https://user-images.githubusercontent.com/16518346/97843658-a4739b00-1d24-11eb-9e1c-70392493ff2c.png)
![image](https://user-images.githubusercontent.com/16518346/97843692-b3f2e400-1d24-11eb-96cf-bf2765c8c87c.png)

**Comment by i-curve** [comment]
+1 没有图片

**Comment by FRZ5201314** [comment]
个体修复办法：
  将C:\Users\thisf\.vscode\extensions\runnerup.super-encourager-4.0.1\src\command\handler\image-command.js文件打开，在“let vscodeImagePath = vscode.Uri.file(cacheImagePath)”前插入以下内容即可：
     var imageData = fs.readFileSync(cacheImagePath)
    const base64Data = Buffer.from(imageData).toString('base64');
    return "data:image/jpg;base64," + base64Data
![Uploading Dingtalk_20201123091113.jpg…]()

**Comment by weiweiwei256** [comment]
修复啦 不好意思 原因是：baidu做了修改禁止爬虫 另外 vscode 插件的通信协议也更新
