### ISSUE TITLE
希望提示的文字可以更加有趣生动.

### ISSUE THREAD

**Issue by liguobao** [weiweiwei256/super-encourager#2]
可以考虑使用一言的API, https://hitokoto.cn/api
如: https://v1.hitokoto.cn/?c=b

**Comment by weiweiwei256** [comment]
谢谢 你的建议  我会尽快调研   国庆假后会给你答复   如果采用  会在贡献者里增加你的名字 再次感谢

**Comment by liguobao** [comment]
大哥搞不搞呀。。
这个一个晚上就搞定的了啊。

**Comment by weiweiwei256** [comment]
搞啊稿啊  4号已经搞完了  还有其他的事  明天发版  代码在dev分支

**Comment by weiweiwei256** [comment]
v2.0.1 已支持
