### ISSUE TITLE
图片尺寸问题

### ISSUE THREAD

**Issue by Elisony** [weiweiwei256/super-encourager#3]
建议把图片尺寸调大，铺满页面最好，图片实在是太小了，加上提醒声音更加完美了

**Comment by weiweiwei256** [comment]
谢谢 你得建议  图片我会增加默认尺寸(接近铺满屏幕)  国庆后支持   声音得话 我得再考虑下 是否合适  因为我不希望太侵入   而且如果   有人外放影响到周边得人也不太好    所以即使增加声音  提示声音也得仔细选择  
再次感谢您的建议  一经采用   将会更新说明中  留下您的名字

**Comment by Elisony** [comment]
现在发现一个问题，就是提示不会跟其他插件一样会自动弹出，而是每次都要手动点击召唤有点蛋疼！！！


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Elison



---原始邮件---
发件人: "RUNNERUP"<notifications@github.com&gt;
发送时间: 2019年9月29日(星期日) 上午10:41
收件人: "weiweiwei256/super-encourager"<super-encourager@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Elison"<1248647469@qq.com&gt;;
主题: Re: [weiweiwei256/super-encourager] 图片尺寸问题 (#3)



谢谢 你得建议  图片我会增加默认尺寸(接近铺满屏幕)  国庆后支持   声音得话 我得再考虑下 是否合适  因为我不希望太侵入   而且如果   有人外放影响到周边得人也不太好    所以即使增加声音  提示声音也得仔细选择
 再次感谢您的建议&nbsp; 一经采用&nbsp;&nbsp; 将会更新说明中&nbsp; 留下您的名字

**Comment by weiweiwei256** [comment]
这边设置的策略是:  固定的时间间隔/特定的自然时间   右下就会自动显示召唤提示框,点击即可
如果提示框不出现,那就是bug 得把日志发给我  
如果觉得最后点击一下  很麻烦  这个就是策略问题   我们再聊   之前是到时间自动显示图片的  但是绝的太侵入  就改成提示框的形式了.

**Comment by Elisony** [comment]
我看了其他鼓励师插件的基本上都是弹出的，因为你多了一个提示框需要去点击基本上没人去走一步会变得麻烦了



---原始邮件---
发件人: "RUNNERUP"<notifications@github.com&gt;
发送时间: 2019年9月29日(星期日) 中午11:03
收件人: "weiweiwei256/super-encourager"<super-encourager@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Elison"<1248647469@qq.com&gt;;
主题: Re: [weiweiwei256/super-encourager] 图片尺寸问题 (#3)



这边设置的策略是:  固定的时间间隔/特定的自然时间   右下就会自动显示召唤提示框,点击即可
 如果提示框不出现,那就是bug 得把日志发给我
 如果觉得最后点击一下  很麻烦  这个就是策略问题   我们再聊   之前是到时间自动显示图片的  但是绝的太侵入  就改成提示框的形式了.

**Comment by weiweiwei256** [comment]
v2.0.1 增加属性选择  superencourager.needTip 来设置是否在召唤前 显示提示

**Comment by Elisony** [comment]
今天已经体验到了，谢谢



---原始邮件---
发件人: "RUNNERUP"<notifications@github.com&gt;
发送时间: 2019年10月8日(星期二) 下午2:14
收件人: "weiweiwei256/super-encourager"<super-encourager@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Elison"<1248647469@qq.com&gt;;
主题: Re: [weiweiwei256/super-encourager] 图片尺寸问题 (#3)



v2.0.1 增加属性选择  superencourager.needTip 来设置是否在召唤前 显示提示

**Comment by sniperrenren** [comment]
图片不显示 什么鬼 
右侧本应该展示图片的地方 没有显示图片     只显示一个图片挂掉的图标
