### ISSUE TITLE
菜鸟问题：那个关键字可以设置多个么

### ISSUE THREAD

**Issue by SSFsystem** [weiweiwei256/super-encourager#4]
想输入很多美女的名字，不知道用什么分隔符。用了顿号，搜索出奇怪的人了

**Comment by SSFsystem** [comment]
我的错，忘记一般分隔都是逗号了

**Comment by weiweiwei256** [comment]
同一时间 只能设置一个   你可以多设置几个  然后手动进行切换  有命令   
当然你的建议我会考虑下   支持同时设置多个  我先从多个关键字中 随机一个  然后再从获取的图片中随机
你的建议还是挺好的  这样的话 也没有切换的问题了

**Comment by SSFsystem** [comment]
期待更新###

**Comment by weiweiwei256** [comment]
该功能已经提供，并且还有新增很多其他的功能。期待你提更多有价值的建议
