### ISSUE TITLE
为什么一出来就是test测试页啊

### ISSUE THREAD

**Issue by zhaopengkun1996** [weiweiwei256/super-encourager#7]
``
![image](https://user-images.githubusercontent.com/44956145/69842940-4cc0ea00-12a0-11ea-860d-8148bcd415a8.png)

**Comment by weiweiwei256** [comment]
我的问题  周末改好   上周发版后 紧急修复了个bug   这里处理粗错了  见谅见谅

**Comment by weiweiwei256** [comment]
已解决
