### ISSUE TITLE
那个好奇能不能支持每次展示时，展示的是自己本地的图片

### ISSUE THREAD

**Issue by SSFsystem** [weiweiwei256/super-encourager#8]
请问能不能选择本地的图片展示，自动搜索有时比较坑。例如搜杨超越，已经出来好几次表情包转发了

**Comment by weiweiwei256** [comment]
你可以把本地的照片放到  我的最爱里    然后   关键字只设置我的最爱  就可以了   本地图片的地址可以通过  F1:  进入命令空间      输入super.showPath查看
关于现在获取的美图我的随机方式 我再优化下   现在的还有点问题   预计这周末会发下一版。当然还有其他的功能更新。谢谢支持哈
