### ISSUE TITLE
我收藏了很多图片，在哪儿查看呢？

### ISSUE THREAD

**Issue by huaiguoguo** [weiweiwei256/super-encourager#9]
我收藏了很多图片，在哪儿查看呢？

**Comment by weiweiwei256** [comment]
可通过在关键字增加 我的最爱  收藏的图片就概率展示了   
收藏地址在 vscode公共资源目录 可通过命令： super:showPath查看
[image](https://user-images.githubusercontent.com/16871471/81097576-b2459080-8f3a-11ea-8e89-d8c18419919d.png)
